### ISSUE TITLE
Kople kategorier av registrerte og kategorier av personopplysninger

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/records-of-processing-activities-gui#108]
Hentet fra behov:
https://github.com/Informasjonsforvaltning/behov/issues/475

om: behandlingsansvarlig som registrerer i protokoll
Ønsker jeg å: knytte kategorier av registrerte og kategorier av personopplysninger sammen
Slik at: det fremgår klart hvilke personopplysninger vi registrerer om den enkelte kategori av registrerte.

Relatert til epos:
TODO: Roger oppretter nytt EPOS "Utvidelse av Protokoll over Behandlingsaktiviteter" og knytter alle brukerhistorier som er ønskelig å få gjennomført til dette eposet.

Lenke til trådskisser:
Registrere protokoll kategorier av registrerte.pdf

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/register/protocol/github475.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig Databehandlerne er pålagt å kunne beskrive behandlingsaktiviteter som utføres under deres ansvar.

Akseptansekriterie:

- I feltet 'kategorier av registrerte' skal bruker kunne skrive inn hva som helst.
- I feltet 'kategorier av personopplysninger' skal bruker kunne legge inn 1 til N antall labels, der de skilles ved trykk på ENTER
- Feltene ''kategorier av registrerte' og 'kategorier av personopplysninger' skal eksistere i par.
- Begge feltene er obligatoriske, det betyr at bruker må fylle ut minst et par.
- Hjelpetekst for hele kategorien skal være: ".........................@Roger".
- Dersom bruker legger til "ny kategori av registrerte og kategorier av personopplysninger" skal det dukke opp to nye felter, altså et nytt par.
- Dersom bruker "sletter kategorier" skal paret fjernes.
- Dersom bruker ikke fyller ut begge feltene i parret så skal det vises en valideringsfeil.
- NB! Feltene skal fremstå som et par i rapporten.

Scenario: Bruker skal registrere labels i 'kategorier av personopplysninger'
Gitt at bruker står i feltet 'kategorier av personopplysninger'
og bruker har skrevet inn noe tekst
når bruker klikker på ENTER
Så skal det vises en label med den teksten bruker har skrevet inn

**Comment by lillelars** [comment]
@joebrreg  klar til godkjenning (og så kan vi også flytte behovet til klar til akseptanse)

**Comment by joebrreg** [comment]
@lillelars jeg godkjenner, men vi burde ta tekstendringene også før de går videre i behovsprosessen
