### ISSUE TITLE
Diverse tekstendringer - behandlingsaktiviteter

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/records-of-processing-activities-gui#116]
- [x] Under Felles behandlingsansvar - endre fra "kontaktperson" til "kontaktpunkt"
![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/05dbaf95-8031-454a-9375-575250c50226)

- [x] Under Behandlingsaktiviteter - endre tre steder til "Henvisning til annen lovgivning"
![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/d38ba27e-2bf5-478d-b2a4-5de1e8a15d5e)

- [x] Under Behandlingsaktiviteter - endre til "Funksjons- eller virksomhetsområde" og rett opp hjelpetekst "Skriv inn hvilket overordnet funksjons-eller virksomhetsområde behandlingen faller inn under"
![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/b96f9fbf-3948-4729-89b4-2edc8441b39a)

- [x] Under Personopplysninger - endre tittel i siste felt til "System i virksomheten som behandler personopplysningene"
![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/51bd7b84-4bbb-4491-80cc-3719fd2a06c6)

**Comment by lillelars** [comment]
Lukker denne. German fikser siste tekstendringsfeil.
