### ISSUE TITLE
Klarer ikke lagre lenke i processing activities

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/records-of-processing-activities-gui#169]
Dette feltet blir ikke lagret:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/59843826-d1b3-4867-9e66-f71af4299458)

Legg in lenke:
https://elements.mattilsynet.no/elements/rm/MATTILSYNET_ELEMENTS#nav=/ephorte/-1013/-602/14949861/view/documents/15967532/preview

**Comment by jeffreiffers** [comment]
Klarer ikke å gjenskape problemet. Lukker saken.
