### ISSUE TITLE
Endre spørsmål i bolk Behandlingsansvarlig

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/records-of-processing-activities-gui#91]
I bolk Behandlingsansvarlig: 
endre spørsmål "Er behandlingsansvarlig eller databehandler etablert utenfor EU/EØS?" 
til "Er behandlingsansvarlig etablert utenfor EU/EØS?"	

![image](https://user-images.githubusercontent.com/39513382/82803198-65d9da80-9e80-11ea-8b93-2c3127323773.png)

**Comment by lillelars** [comment]
Testet i staging. godkjent
