### ISSUE TITLE
Ny (og endring av) behandlingsaktivitet - skal være default lukket

### ISSUE THREAD

**Issue by azaxarov** [Informasjonsforvaltning/records-of-processing-activities-gui#92]
@RogerSOlsen commented on [Wed Mar 25 2020](https://github.com/Informasjonsforvaltning/fdk/issues/3053)

Første seksjon er åpnet. Dette ønskes å være default lukket.

Ønsker default lukket (slik):
![image](https://user-images.githubusercontent.com/39513382/82803519-f9131000-9e80-11ea-8011-e38e3c0f94ff.png)

**Comment by lillelars** [comment]
Testet og godkjent i staging,. Lukker denne.
