### ISSUE TITLE
Protokoll over behandlingsaktiviteter: Gjenåpne tilgang for skrivebruker til denne

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/records-of-processing-activities-gui#93]
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/bbf47ff3-8e65-4793-8dcc-ff31c4ea25fc)

**Comment by azaxarov** [comment]
Issue moved to [Informasjonsforvaltning/dataset-catalogue-gui #48](https://github.com/Informasjonsforvaltning/dataset-catalogue-gui/issues/48) via [**ZenHub**](https://www.zenhub.com/)
